FROM python:3.13.7-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

ADD pyproject.toml .
RUN uv pip install --system -r pyproject.toml

ADD app/ /app

RUN chmod +x /app/start.sh

EXPOSE 8080

CMD ["/app/start.sh"]